import useWebTitle from '@/hook/useWebTitle';
import Head from 'next/head'
import Script from 'next/script';
import Front from './FrontPage';




export default function Home() {
  useWebTitle('Gym Home Page')
  return (
    <>
      <Head>
        <title>GYM Baran Live Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Front></Front>

      {/*  Anmation Link */}
    </>
  )
}
